---
categories:
- ""
- ""
date: "2017-10-31T22:42:51-05:00"
description: Analysis of top rated movies and directors
draft: false
image: movies.jpg
keywords: ""
slug: blog7
title: IMDB movies
---



<p>We will look at a subset sample of movies, taken from the <a href="https://www.kaggle.com/carolzhangdc/imdb-5000-movie-dataset">Kaggle IMDB 5000 movie dataset</a></p>
<pre class="r"><code>movies &lt;- read_csv(here::here(&quot;data&quot;, &quot;movies.csv&quot;))
glimpse(movies)</code></pre>
<pre><code>## Rows: 2,961
## Columns: 11
## $ title               &lt;chr&gt; &quot;Avatar&quot;, &quot;Titanic&quot;, &quot;Jurassic World&quot;, &quot;The Ave...
## $ genre               &lt;chr&gt; &quot;Action&quot;, &quot;Drama&quot;, &quot;Action&quot;, &quot;Action&quot;, &quot;Action&quot;...
## $ director            &lt;chr&gt; &quot;James Cameron&quot;, &quot;James Cameron&quot;, &quot;Colin Trevor...
## $ year                &lt;dbl&gt; 2009, 1997, 2015, 2012, 2008, 1999, 1977, 2015,...
## $ duration            &lt;dbl&gt; 178, 194, 124, 173, 152, 136, 125, 141, 164, 93...
## $ gross               &lt;dbl&gt; 7.61e+08, 6.59e+08, 6.52e+08, 6.23e+08, 5.33e+0...
## $ budget              &lt;dbl&gt; 2.37e+08, 2.00e+08, 1.50e+08, 2.20e+08, 1.85e+0...
## $ cast_facebook_likes &lt;dbl&gt; 4834, 45223, 8458, 87697, 57802, 37723, 13485, ...
## $ votes               &lt;dbl&gt; 886204, 793059, 418214, 995415, 1676169, 534658...
## $ reviews             &lt;dbl&gt; 3777, 2843, 1934, 2425, 5312, 3917, 1752, 1752,...
## $ rating              &lt;dbl&gt; 7.9, 7.7, 7.0, 8.1, 9.0, 6.5, 8.7, 7.5, 8.5, 7....</code></pre>
<p>Besides the obvious variables of <code>title</code>, <code>genre</code>, <code>director</code>, <code>year</code>, and <code>duration</code>, the rest of the variables are as follows:</p>
<ul>
<li><code>gross</code> : The gross earnings in the US box office, not adjusted for inflation</li>
<li><code>budget</code>: The movie’s budget</li>
<li><code>cast_facebook_likes</code>: the number of facebook likes cast memebrs received</li>
<li><code>votes</code>: the number of people who voted for (or rated) the movie in IMDB</li>
<li><code>reviews</code>: the number of reviews for that movie</li>
<li><code>rating</code>: IMDB average rating</li>
</ul>
<pre class="r"><code>skim(movies)</code></pre>
<p>Skimming allows us to see if there are missing values. We can conclude that this is not the case. Moreover, we found that the data consists of 2961 observations across 11 variables. Considering there are 2907 unique titles, we can conclude that there are 54 non-unique movie titles. Furthermore, it is not surprising that there are numerous duplicates for the other variables such as genre and director, as genres consist of more than 1 movie and movie directors often direct more than 1 movie.</p>
<pre class="r"><code>#We produce a table with the count of movies by genre, ranked in descending order
movie_genre &lt;- movies %&gt;%
  group_by(genre) %&gt;%
  count(sort=TRUE)
movie_genre</code></pre>
<pre><code>## # A tibble: 17 x 2
## # Groups:   genre [17]
##    genre           n
##    &lt;chr&gt;       &lt;int&gt;
##  1 Comedy        848
##  2 Action        738
##  3 Drama         498
##  4 Adventure     288
##  5 Crime         202
##  6 Biography     135
##  7 Horror        131
##  8 Animation      35
##  9 Fantasy        28
## 10 Documentary    25
## 11 Mystery        16
## 12 Sci-Fi          7
## 13 Family          3
## 14 Musical         2
## 15 Romance         2
## 16 Western         2
## 17 Thriller        1</code></pre>
<pre class="r"><code># We produce a table with the average gross earning and budget (`gross` and `budget`) by genre. We calculate a variable `return_on_budget` which shows how many $ did a movie make at the box office for each $ of its budget. Ranked genres by this `return_on_budget` in descending order
budget_gross_return &lt;- movies %&gt;% 
  group_by(genre) %&gt;% 
  summarize(avg_gross=mean(gross),
            avg_budget=mean(budget),
            return_on_budget=avg_gross/avg_budget)
view(budget_gross_return)

# We produce a table that shows the top 15 directors who have created the highest gross revenue in the box office. Don&#39;t just show the total gross amount, but also the mean, median, and standard deviation per director.

best_directors &lt;- movies %&gt;% 
  group_by(director) %&gt;% 
  summarize(total_gross=sum(gross),
            avg_gross=mean(gross),
            med_gross=median(gross),
            sd_gross=sd(gross)) %&gt;% 
  arrange(desc(total_gross)) %&gt;% 
  slice(1:15)
view(best_directors)

#Finally, ratings. We produce a table that describes how ratings are distributed by genre. We don&#39;t want just the mean, but also, min, max, median, SD and some kind of a histogram or density graph that visually shows how ratings are distributed. 

genre_ratings &lt;- movies %&gt;% 
  group_by(genre) %&gt;% 
  summarize(avg_rating=mean(rating),
            min_rating=min(rating),
            max_rating=max(rating),
            med_rating=median(rating),
            sd_rating=sd(rating))
view(genre_ratings) 

ggplot(movies, aes(x=rating)) +
  geom_histogram(fill=&quot;#DD0000&quot;, bins=20) + 
  ggtitle(&quot;Distribution of ratings across different genres&quot;) +
  facet_wrap(~genre) +
  theme(panel.background = element_rect(colour = &quot;White&quot;)) + 
  theme_light() </code></pre>
<p><img src="/blogs/blog7_files/figure-html/count_movies_genre-1.png" width="648" style="display: block; margin: auto;" />
We chose to plot histograms, as this shows us both the count of movies as well as the distributions. However, for some genres, the data provided is insufficient to make any conclusions (For example: Family, Romance, Sci-fi,). We adjusted the bins to allow for a clearer representation of the data.</p>
<div id="use-ggplot-to-answer-the-following" class="section level2">
<h2>Use <code>ggplot</code> to answer the following</h2>
<p><em>Examine the relationship between <code>gross</code> and <code>cast_facebook_likes</code>. Produce a scatterplot and write one sentence discussing whether the number of facebook likes that the cast has received is likely to be a good predictor of how much money a movie will make at the box office. What variable are you going to map to the Y- and X- axes?</em></p>
<pre class="r"><code>ggplot(movies, aes(x=gross, y=cast_facebook_likes)) + 
  geom_point(color=&quot;#DD0000&quot;) + 
  labs(x=&quot;Gross Income&quot;, y=&quot;Facebook likes of the cast&quot;) + 
  ggtitle(&quot;Relationship between the amount of Facebook likes of the cast and \nthe Gross revenue of the movie&quot;) + 
  scale_x_log10() + scale_y_log10() +
  geom_smooth(method= &#39;lm&#39;, se=FALSE) +
  theme(panel.background = element_rect(colour = &quot;White&quot;)) + 
  theme_light() +
  NULL</code></pre>
<p><img src="/blogs/blog7_files/figure-html/gross_on_fblikes-1.png" width="648" style="display: block; margin: auto;" /></p>
<pre class="r"><code>cor.test(movies$gross, movies$cast_facebook_likes)</code></pre>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  x and y
## t = 12, df = 2959, p-value &lt;2e-16
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.179 0.247
## sample estimates:
##   cor 
## 0.213</code></pre>
<p>After plotting the two variables and running a correlation test, it is clear that, though the correlation is low at 0.213, it is significant (with a p&lt;0.01). This means that having a cast with many facebook like affects the gross revenue, but not too much</p>
<p><em>Examine the relationship between <code>gross</code> and <code>budget</code>. Produce a scatterplot and write one sentence discussing whether budget is likely to be a good predictor of how much money a movie will make at the box office.</em></p>
<pre class="r"><code>ggplot(movies, aes(x=gross, y=budget)) + 
  geom_point(color=&quot;#DD0000&quot;) + 
  labs(x= &quot;Gross revenue&quot;, y= &quot;Movie budget&quot;)+
  ggtitle(&quot;Relationship between the amount spend on the movie production and \nthe Gross revenue of the movie&quot;) +
  scale_x_log10() + scale_y_log10() +
  geom_smooth(method=&#39;lm&#39;, se=FALSE) +
  theme(panel.background = element_rect(colour = &quot;White&quot;)) + 
  theme_light() +
  NULL</code></pre>
<p><img src="/blogs/blog7_files/figure-html/gross_on_budget-1.png" width="648" style="display: block; margin: auto;" /></p>
<pre class="r"><code>cor_test(movies$gross, movies$budget)</code></pre>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  x and y
## t = 45, df = 2959, p-value &lt;2e-16
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.619 0.662
## sample estimates:
##   cor 
## 0.641</code></pre>
<p>Once more, we ran a scatterplot as well as a correlation test. This time too the result was highly significant (p&lt;0.01), but the correlation was much higher at 0.641. This means that spending more on the production of the movie has quite a large effect on its gross revenue.</p>
<p><em>Examine the relationship between <code>gross</code> and <code>rating</code>. Produce a scatterplot, faceted by <code>genre</code> and discuss whether IMDB ratings are likely to be a good predictor of how much money a movie will make at the box office. Is there anything strange in this dataset?</em></p>
<pre class="r"><code>ggplot(movies, aes(x=gross, y=rating)) + 
  geom_point(color=&quot;#DD0000&quot;) + 
  labs(x= &quot;Gross revenue&quot;, y= &quot;Movie rating on IMDB&quot;)+
  ggtitle(&quot;Relationship between the rating a movie has on IMDB and \nthe Gross revenue of the movie&quot;) +
  scale_x_log10() +
  facet_wrap(~genre) +
  theme(panel.background = element_rect(colour = &quot;White&quot;)) + 
  theme_light() +
  geom_smooth(method=&#39;lm&#39;, se=FALSE) +
  NULL</code></pre>
<p><img src="/blogs/blog7_files/figure-html/gross_on_rating-1.png" width="648" style="display: block; margin: auto;" /></p>
<pre class="r"><code>cor_test(movies$gross, movies$rating)</code></pre>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  x and y
## t = 15, df = 2959, p-value &lt;2e-16
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.236 0.303
## sample estimates:
##   cor 
## 0.269</code></pre>
<p>Running a correlation test between gross returns and movie ratings reveals that there is a small, but significant positive correlation between the both (cor=0.269, p&lt;0.01). However, when we divide the movies per genre and put this correlation in a scatterplot, we can notice a discrepancy within genres. Due to the lack of data, we can omit genres such as family, musical, romance, thriller, western, etc. However, even within the genres with many data points, there is a significant difference in correlation coefficients. Action movies clearly have the highest correlation between movie ratings and the gross revenue, whilst genres like comedy, crime and drama are much less affected. This can possibly be explained by action movies relying heavily on special effects and expensive CGI. Meanwhile, dramas, comedies and crime do not necessarily need this budget to convey the message. Moreover, there are more subsections within the genres comedy, crime and drama, compared to action. For the former, the audiences are likely very different and rate movies on a different scale, based on more subjective factors.</p>
</div>
